version: '3.7'
services:

  nginx:
    image: nginx:1.14.1
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - "backend"
      - "frontend"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse-proxy

  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "9000:9000"
    restart: always
    networks:
      - reverse-proxy
    
  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports: 
      - "4200:80"
    restart: always
    networks: 
      - reverse-proxy

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   networks:
  #     - reverse-proxy

networks:
  reverse-proxy:
    driver: bridge